"""Phase 5 (Web UI adapter): executes an approved plan's steps.

Only file_write/file_delete/git_commit/git_push run here directly, against
a dedicated per-plan clone — these are structured, already mediated by the
Action Object + risk/policy check in planner.py, not arbitrary commands.
git_push additionally needs real network egress to reach GitHub.

shell_exec is the one action type that runs genuinely untrusted content (an
LLM-authored command), so it's routed through the Phase 0 sandbox
(infra/sandbox: an isolated, --network none, resource-limited container)
via `docker exec` into the already-running sandbox container, rather than
running on the host.
"""

import json
import subprocess
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings
from app.db.models import Action, Plan, Repository
from app.github_client import clone_repo, create_pull_request, get_default_branch, push_branch
from app.pipeline import record_event

SHELL_EXEC_TIMEOUT = 90


class ExecutionError(Exception):
    pass


def _working_dir(plan: Plan) -> Path:
    return Path(settings.plans_dir) / str(plan.id)


def _ensure_working_dir(plan: Plan, repo: Repository) -> Path:
    wd = _working_dir(plan)
    if not wd.exists():
        clone_repo(repo.clone_url, wd)
        subprocess.run(["git", "checkout", "-b", plan.branch_name], cwd=str(wd), check=True, capture_output=True, text=True)
        subprocess.run(["git", "config", "user.email", "ambit@localhost"], cwd=str(wd), check=True)
        subprocess.run(["git", "config", "user.name", "Ambit"], cwd=str(wd), check=True)
    return wd


def _run_in_sandbox(command: str) -> dict:
    result = subprocess.run(
        ["docker", "exec", settings.sandbox_container_name, "python3", "runner.py", command],
        capture_output=True,
        text=True,
        timeout=SHELL_EXEC_TIMEOUT,
    )
    if result.returncode != 0:
        raise ExecutionError(f"sandbox exec itself failed: {result.stderr}")
    return json.loads(result.stdout)


async def _run_action(action: Action, wd: Path, plan: Plan, repo: Repository) -> dict:
    """Returns an output payload to record on success; raises ExecutionError on failure."""
    if action.action_type == "file_write":
        target = wd / action.target
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(action.action_metadata["content"], encoding="utf-8")
        return {"wrote_bytes": len(action.action_metadata["content"])}

    if action.action_type == "file_delete":
        target = wd / action.target
        if target.exists():
            target.unlink()
        return {}

    if action.action_type == "shell_exec":
        result = _run_in_sandbox(action.target)
        if result.get("exit_code") != 0:
            raise ExecutionError(f"command exited {result.get('exit_code')}: {result.get('stderr')}")
        return result

    if action.action_type == "git_commit":
        message = action.action_metadata.get("commit_message", "Ambit automated change")
        add = subprocess.run(["git", "add", "-A"], cwd=str(wd), capture_output=True, text=True)
        if add.returncode != 0:
            raise ExecutionError(f"git add failed: {add.stderr}")
        status = subprocess.run(["git", "status", "--porcelain"], cwd=str(wd), capture_output=True, text=True)
        if not status.stdout.strip():
            return {"note": "nothing to commit"}
        commit = subprocess.run(["git", "commit", "-m", message], cwd=str(wd), capture_output=True, text=True)
        if commit.returncode != 0:
            raise ExecutionError(f"git commit failed: {commit.stderr}")
        return {"commit_output": commit.stdout}

    if action.action_type == "git_push":
        if not settings.github_token:
            raise ExecutionError("GITHUB_TOKEN is not configured — cannot push or open a PR")
        try:
            push_branch(wd, plan.branch_name, repo.clone_url, settings.github_token)
        except subprocess.CalledProcessError as exc:
            raise ExecutionError(f"git push failed: {exc.stderr}") from exc

        base_branch = repo.default_branch or await get_default_branch(repo.clone_url, settings.github_token)
        repo.default_branch = base_branch
        pr = await create_pull_request(
            settings.github_token,
            repo.clone_url,
            head_branch=plan.branch_name,
            base_branch=base_branch,
            title=f"Ambit: {plan.task_description}"[:255],
            body=(
                f"Automated change generated by Ambit's web UI adapter.\n\n"
                f"**Task:** {plan.task_description}\n\n"
                f"Every step in this plan went through Ambit's risk/policy pipeline before executing. "
                f"AI-generated — review before merging."
            ),
        )
        plan.pr_url = pr["html_url"]
        return {"pr_url": pr["html_url"]}

    raise ExecutionError(f"no executor for action_type '{action.action_type}'")


async def execute_action(session: AsyncSession, action: Action, plan: Plan, repo: Repository) -> None:
    action.status = "executing"
    await record_event(session, action.id, "execution_started", {})
    await session.commit()

    wd = _ensure_working_dir(plan, repo)

    try:
        output = await _run_action(action, wd, plan, repo)
    except Exception as exc:  # noqa: BLE001 - must not crash the plan loop; failure is a normal outcome
        action.status = "failed"
        await record_event(session, action.id, "execution_failed", {"error": str(exc)})
        await session.commit()
        raise
    else:
        action.status = "completed"
        await record_event(session, action.id, "execution_completed", {"output": output})
        await session.commit()


async def run_ready_actions(session: AsyncSession, plan: Plan) -> None:
    """Executes every currently-unblocked, approved step, then recurses to
    pick up newly-unblocked steps, until the plan is fully executed, blocked
    on a pending approval, or has failed."""
    repo = await session.get(Repository, plan.repository_id)

    while True:
        all_actions = (
            await session.execute(select(Action).where(Action.plan_id == plan.id))
        ).scalars().all()

        if any(a.status == "failed" for a in all_actions) and plan.status != "failed":
            # Reached on re-entry (e.g. approving a sibling step) after a
            # prior run already failed and returned — the actual error
            # message from that run was already recorded on plan.error then.
            plan.status = "failed"
            await session.commit()
            return

        if any(a.status == "denied" for a in all_actions):
            plan.status = "failed"
            plan.error = "a step was denied by policy"
            await session.commit()
            return

        completed_ids = {str(a.id) for a in all_actions if a.status == "completed"}
        ready = [
            a
            for a in all_actions
            if a.status == "approved" and all(dep in completed_ids for dep in a.depends_on)
        ]

        if not ready:
            break

        failure: str | None = None
        for action in ready:
            try:
                await execute_action(session, action, plan, repo)
            except Exception as exc:  # noqa: BLE001 - also recorded on the action's event log
                failure = f"{action.target or action.action_type}: {exc}"
                break

        if failure is not None:
            plan.status = "failed"
            plan.error = failure
            await session.commit()
            return

    all_actions = (
        await session.execute(select(Action).where(Action.plan_id == plan.id))
    ).scalars().all()

    if all(a.status == "completed" for a in all_actions):
        plan.status = "completed"
    elif any(a.status == "pending" for a in all_actions):
        plan.status = "pending_approval"
    else:
        plan.status = "executing"
    await session.commit()
