"""Phase 7: builds the PR body from the plan's actual steps, risk scores,
and approval trail. Deterministic string formatting from data already on
the Action/Approval rows -- not another LLM call, since this is a factual
summary of what already happened, not something that needs generating.
"""

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from app.db.models import Action, Plan

TEST_RUN_PURPOSE = "test_run"


async def build_pr_body(session: AsyncSession, plan: Plan) -> str:
    result = await session.execute(
        select(Action)
        .where(Action.plan_id == plan.id)
        .options(selectinload(Action.approvals))
        .order_by(Action.created_at)
    )
    actions = result.scalars().all()

    lines = [
        "Automated change generated by Ambit's web UI adapter.",
        "",
        f"**Task:** {plan.task_description}",
        "",
        "AI-generated — review before merging.",
        "",
        "## Steps",
        "",
        "| Step | Target | Risk | Status |",
        "|---|---|---|---|",
    ]
    for a in actions:
        risk = f"{a.risk_level} ({a.risk_score})" if a.risk_level else "—"
        target = a.target or "(auto)"
        lines.append(f"| {a.action_type} | `{target}` | {risk} | {a.status} |")

    approved_steps = [a for a in actions if a.approvals]
    if approved_steps:
        lines += ["", "## Approval trail", ""]
        for a in approved_steps:
            for appr in a.approvals:
                detail = f" — {appr.reason}" if appr.reason else ""
                lines.append(f"- **{a.action_type}** (`{a.target}`): {appr.decision} by {appr.approver}{detail}")

    test_step = next(
        (a for a in actions if a.action_type == "shell_exec" and a.action_metadata.get("purpose") == TEST_RUN_PURPOSE),
        None,
    )
    lines += ["", "## Tests", ""]
    if test_step is None:
        lines.append("No test-run step in this plan (non-code change, or no existing test setup detected).")
    else:
        lines.append(f"`{test_step.target}` — **{test_step.status}**")

    return "\n".join(lines)
