"""add plans table and action plan_id/depends_on

Revision ID: 1762498f1d2a
Revises: 296b683349df
Create Date: 2026-08-05 17:04:38.170808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1762498f1d2a'
down_revision: Union[str, None] = '296b683349df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('task_description', sa.String(), nullable=False),
    sa.Column('branch_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('pr_url', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('actions', sa.Column('plan_id', sa.UUID(), nullable=True))
    op.add_column(
        'actions',
        sa.Column('depends_on', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'),
    )
    op.alter_column('actions', 'depends_on', server_default=None)
    op.create_foreign_key(None, 'actions', 'plans', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actions', type_='foreignkey')
    op.drop_column('actions', 'depends_on')
    op.drop_column('actions', 'plan_id')
    op.drop_table('plans')
    # ### end Alembic commands ###
