"""add repository_docs table for architecture generation

Revision ID: 296b683349df
Revises: 4132995625c8
Create Date: 2026-08-04 23:47:21.101899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '296b683349df'
down_revision: Union[str, None] = '4132995625c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_docs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('readme_markdown', sa.String(), nullable=False),
    sa.Column('sequence_diagram_title', sa.String(), nullable=False),
    sa.Column('sequence_diagram_mermaid', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repository_docs')
    # ### end Alembic commands ###
