"""add plan reverts_action_id for rollback

Revision ID: a967d204fedf
Revises: 1762498f1d2a
Create Date: 2026-08-05 18:03:47.736752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a967d204fedf'
down_revision: Union[str, None] = '1762498f1d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('reverts_action_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'plans', 'actions', ['reverts_action_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plans', type_='foreignkey')
    op.drop_column('plans', 'reverts_action_id')
    # ### end Alembic commands ###
